use serde::{Deserialize, Serialize};

/// Messages sent from client to server
#[derive(Debug, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ClientMessage {
    /// Encrypted sync data to broadcast to household. `correlation_id` is
    /// generated by the sender and used by the server to dedupe on retry
    /// and by the sender to match the resulting `SyncReceived` ack.
    Sync {
        payload: String,
        correlation_id: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        entity_type: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        change_type: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        description: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        recipients: Option<Vec<String>>,
    },

    /// Online status update
    Presence { online: bool },

    /// Keepalive ping
    Ping,

    /// Acknowledge receipt of a message
    Ack { message_id: String },

    /// Request sync status (pending messages from this member)
    SyncStatusRequest,
}

/// Messages sent from server to client
#[derive(Debug, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ServerMessage {
    /// Sync data from another device
    Sync {
        from: String,
        payload: String,
        /// Server-assigned message ID for acknowledgment
        message_id: String,
        /// Optional recipient filter (member IDs); if set, only these members receive
        #[serde(skip_serializing_if = "Option::is_none")]
        recipients: Option<Vec<String>>,
        /// Routing hint so the client can distinguish a call signal from a CRDT
        /// frame without decrypting (e.g. entity_type:"call").
        #[serde(skip_serializing_if = "Option::is_none")]
        entity_type: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        change_type: Option<String>,
    },

    /// Device presence update
    Presence {
        device_id: String,
        member_id: String,
        online: bool,
    },

    /// Queued messages delivered on reconnect
    Queued { messages: Vec<QueuedMessage> },

    /// Keepalive pong
    Pong,

    /// Error message
    Error { code: String, message: String },

    /// Sync status response - shows pending changes from this member
    SyncStatus {
        pending_messages: Vec<PendingSyncMessage>,
    },

    /// Notification that a message was delivered to a member
    DeliveryStatus {
        message_id: String,
        member_id: String,
        delivered: bool,
    },

    /// Acknowledgment that a `Sync` message has been persisted on the
    /// server. Sent back to the original sender after `store_pending_message`
    /// succeeds (or on a duplicate, where the existing row's id is returned).
    /// The sender uses `correlation_id` to clear its pending-ack buffer.
    SyncReceived {
        correlation_id: String,
        message_id: String,
    },
}

/// A message that was queued while device was offline
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QueuedMessage {
    pub id: String,
    pub from: String,
    pub payload: String,
    pub timestamp: i64,
    /// Routing hints preserved from the original send so a redelivered frame is
    /// dispatched correctly — e.g. a queued call offer must reach the call
    /// signaling layer, not the CRDT decrypt path (audit #11). Without these
    /// the client couldn't tell a redelivered call frame from a sync frame, so
    /// cold-accept and calls to a reconnecting peer were dead.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub entity_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub change_type: Option<String>,
}

/// Pending sync message with delivery status
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PendingSyncMessage {
    pub id: String,
    pub payload: String,
    pub created_at: i64,
    pub pending_members: Vec<String>,
    pub delivered_members: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub entity_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub change_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_client_message_serialization() {
        let msg = ClientMessage::Sync {
            payload: "encrypted-data".to_string(),
            correlation_id: "corr-1".to_string(),
            entity_type: Some("task".to_string()),
            change_type: Some("create".to_string()),
            description: Some("Created a task".to_string()),
            recipients: None,
        };
        let json = serde_json::to_string(&msg).unwrap();
        assert!(json.contains("\"type\":\"sync\""));
        assert!(json.contains("\"payload\":\"encrypted-data\""));
        assert!(json.contains("\"entity_type\":\"task\""));

        let parsed: ClientMessage = serde_json::from_str(&json).unwrap();
        match parsed {
            ClientMessage::Sync {
                payload,
                entity_type,
                ..
            } => {
                assert_eq!(payload, "encrypted-data");
                assert_eq!(entity_type, Some("task".to_string()));
            }
            _ => panic!("Wrong message type"),
        }
    }

    #[test]
    fn test_client_ack_message() {
        let msg = ClientMessage::Ack {
            message_id: "msg-123".to_string(),
        };
        let json = serde_json::to_string(&msg).unwrap();
        assert!(json.contains("\"type\":\"ack\""));
        assert!(json.contains("\"message_id\":\"msg-123\""));
    }

    #[test]
    fn test_server_message_serialization() {
        let msg = ServerMessage::Presence {
            device_id: "device-1".to_string(),
            member_id: "member-1".to_string(),
            online: true,
        };
        let json = serde_json::to_string(&msg).unwrap();
        assert!(json.contains("\"type\":\"presence\""));

        let parsed: ServerMessage = serde_json::from_str(&json).unwrap();
        match parsed {
            ServerMessage::Presence {
                device_id,
                member_id,
                online,
            } => {
                assert_eq!(device_id, "device-1");
                assert_eq!(member_id, "member-1");
                assert!(online);
            }
            _ => panic!("Wrong message type"),
        }
    }

    #[test]
    fn test_sync_status_message() {
        let msg = ServerMessage::SyncStatus {
            pending_messages: vec![PendingSyncMessage {
                id: "msg-1".to_string(),
                payload: "data".to_string(),
                created_at: 1234567890,
                pending_members: vec!["member-2".to_string()],
                delivered_members: vec!["member-3".to_string()],
                entity_type: Some("task".to_string()),
                change_type: Some("update".to_string()),
                description: Some("Updated task".to_string()),
            }],
        };
        let json = serde_json::to_string(&msg).unwrap();
        assert!(json.contains("\"type\":\"sync_status\""));
        assert!(json.contains("\"pending_messages\""));
        assert!(json.contains("\"entity_type\":\"task\""));
    }
}
